### ISSUE TITLE
Infografía: Programación Concurrente

### ISSUE THREAD

**Issue by Yeim1129** [SistemasTecTlaxiaco/infografia-de-hilos-Yeim1129#2]
[J Manuel_Hernandez A_Tópicos__MULTIHILOS.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-Yeim1129/files/6466376/J.Manuel_Hernandez.A_Topicos__MULTIHILOS.pdf)

**Comment by Nayee123** [comment]
20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
